### ISSUE TITLE
gem install fails on windows 8.1 with ruby 2.1 and devkit

### ISSUE THREAD

**Issue by tetravista** [larskanis/ruby-odbc#1]
when I gem install ruby-odbc, I get the error:

make failed, uncaught signal 11

-- gem install output --

C:\APPS\RUBY21-X64\devkit\mingw\bin>gem install ruby-odbc
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-odbc:
        ERROR: Failed to build gem native extension.

```
current directory: C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/gems/ruby-odbc-0.99997/ext
```

C:/APPS/RUBY21-X64/bin/ruby.exe -r ./siteconf20160322-42016-1v2yhn8.rb extconf.rb
checking for version.h... no
checking for sql.h... yes
checking for sqlext.h... yes
checking for SQLTCHAR in windows.h,sqltypes.h... yes
checking for SQLLEN in windows.h,sqltypes.h... yes
checking for SQLULEN in windows.h,sqltypes.h... yes
checking for odbcinst.h... yes
checking for SQLROWOFFSET in windows.h,sqltypes.h... yes
checking for odbcinst.h... yes
checking for SQLROWSETSIZE in windows.h,sqltypes.h... yes
checking for odbcinst.h... yes
checking for main() in -lodbc32... yes
checking for main() in -lodbccp32... yes
checking for main() in -luser32... yes
creating Makefile

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/ruby-odbc-0.99997/mkmf.log

current directory: C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/gems/ruby-odbc-0.99997/ext
make "DESTDIR=" clean

current directory: C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/gems/ruby-odbc-0.99997/ext
make "DESTDIR="

make failed, uncaught signal 11

Gem files will remain installed in C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/gems/ruby-odbc-0.99997 for inspection.
Results logged to C:/APPS/RUBY21-X64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/ruby-odbc-0.99997/gem_make.out

--ruby version--
C:\APPS\RUBY21-X64\devkit\mingw\bin>ruby -v
ruby 2.1.7p400 (2015-08-18 revision 51632) [x64-mingw32]

--windows version--
C:\APPS\RUBY21-X64\devkit\mingw\bin>ver

Microsoft Windows [Version 6.3.9600]

--- devkit ---
C:\APPS\RUBY21-X64\devkit\mingw\bin>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/apps/ruby21-x64/devkit/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/4.7.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: /home/ruben/mingw-w64/src/gcc/configure --host=x86_64-w64-mingw32 --build=x86_64-linux-gnu --target=x86_64-w64-mingw32 --with-sysroot=/home/ruben/mi
ngw-w64/mingw64mingw64/mingw64 --prefix=/home/ruben/mingw-w64/mingw64mingw64/mingw64 --with-gmp=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-mpfr=/
home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-mpc=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-ppl=/home/ruben/mingw-w64/prereq/x86
_64-w64-mingw32/install --with-cloog=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --disable-ppl-version-check --disable-cloog-version-check --enable-cloog
-backend=isl --with-host-libstdcxx='-static -lstdc++ -lm' --enable-shared --enable-static --enable-threads=win32 --enable-plugins --disable-multilib --enable-languag
es=c,lto,c++,objc,obj-c++,fortran,java --enable-libgomp --enable-fully-dynamic-string --enable-libstdcxx-time --disable-nls --disable-werror --enable-checking=releas
e --with-gnu-as --with-gnu-ld --disable-win32-registry --disable-rpath --disable-werror --with-libiconv-prefix=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/instal
l --with-pkgversion=rubenvb-4.7.2-release --with-bugurl=mingw-w64-public@lists.sourceforge.net CC= CFLAGS='-O2 -march=nocona -mtune=core2 -fomit-frame-pointer -momit
-leaf-frame-pointer' LDFLAGS=
Thread model: win32
gcc version 4.7.2 (rubenvb-4.7.2-release)

**Comment by tetravista** [comment]
I have emailed the original author, but any insight you have would be appreciated

**Comment by larskanis** [comment]
This issue should be solved by more recent versions of this gem. It should at least install fine with RubyInstaller versions since 2.4.
